---
- hosts: all
  become: true
  vars:
   CompanyName: World
   PersonName: KRKREDDY
  tasks:
    - name: Install Apache HTTP Server
      yum: 
        name: httpd
        state: latest
    - name: Start the HTTP Server
      service: 
        name: httpd 
        enabled: yes 
        state: started
    - name: Copy the index.html file
      template: 
        src: index.html
        dest: /var/www//html/index.html
...