---
- name: Create a new EC2 instance
  hosts: localhost
  gather_facts: False

  tasks:

    - name: Create an ec2 instance
      ec2:
         key_name: "{{ keypair }}"
         group: aws-ansible  # security group name
         instance_type: 
         image: 
         wait: true
         region: 
         aws_zone: us-east-2a
         count: 1  # default
         count_tag:
            Name: Tableau Server primary
         instance_tags:
            Name: Tableau Server primary
         vpc_subnet_id: subnet-eec7b786
         assign_public_ip: yes
      register: ec2